spring:
  datasource:
    url: jdbc:mysql://localhost:3306/questionservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate-statistics: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
logging:
  level:
    org.hibernate.stat: debug

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

